Changed terminal prompt

diff --git a/bash/.bashrc.d/bash_prompts b/bash/.bashrc.d/bash_prompts
--- a/bash/.bashrc.d/bash_prompts
+++ b/bash/.bashrc.d/bash_prompts
@@ -1,14 +1,88 @@
-# Prompts
-# PS1='\[\e[1;37m\]\[\e[1;32m\]\u\[\e[0;39m\]:\[\e[1;33m\]\w\[\e[0;39m\] $(__git_ps1 "\[\e[1;35m\]@%s\[\e[0;39m\] ")\[\e[1;37m\]|\[\e[0;39m\]\$'
-# GIT_PS1_SHOWDIRTYSTATE=true
-# export PS1 GIT_PS1_SHOWDIRTYSTATE
-#PS1='\[\e[94m\]\u\[\e[0;49;32m\]@\[\e[91m\]\h\[\e[0m\]:\[\e[33m\]\w\[\e[0m\]\$ '
-#PS1='\[\e[94m\]\u\[\e[91m\]@\[\e[92m\]\h\[\e[0m\]:\[\e[33m\]\w\[\e[0m\] \$ '
+#!/usr/bin/env bash
+# vim:fdm=marker
+# PROMPT {{{
+__prompt_command(){
+local EXIT="$?" # This needs to be first
 
-#PS1='\[\033[0;33m\][\!]\[\e[94m\]\u\[\e[91m\]@\[\e[92m\]\h\[\e[0m\]:\[\e[33m\]\w\[\e[0m\]\n\$ '
-PS1='\n┌\[\e[38;5;85m\]\t\[\e[01;00m\]:\[\e[01;94m\]\u\[\e[0;91m\]@\[\e[01;92m\]\h\[\e[01;0m\]:\[\e[33m\]\w\[\e[0m\]\n└\[\e[35m\][#\!]\[\e[0m\]\$ '
+# Colors
+local RESET='\[\e[0m\]'
+local RED='\[\e[1;31m\]'
+local GREEN='\[\e[1;32m\]'
+local BLUE='\[\e[1;34m\]'
+local PURPLE='\[\e[1;35m\]'
 
-#PS1='\[\033[0;33m\][\!] \[\e[94m\]\u\[\e[91m\]@\[\e[92m\]\h\[\e[0m\]:\[\e[33m\]\w\[\e[0m\]\n \$ '
+PS1="" # start prompt as blank
 
+# exit status check
+if [[ $EXIT -ne 0 ]]; then
+        # red if exit status is non-zero
+        PS1+="${RED}[\w]${RESET}"
+else
+        PS1+="${GREEN}[\w]${RESET}"
+fi
 
-export PS1
+# git directory check
+if git rev-parse --git-dir &>/dev/null; then
+        # check if HEAD is detached from branch
+        if [[ $(git status) =~ "detached" ]]; then
+                BRANCH=$(git status | awk '/detached/ {print $4}')
+        else
+                BRANCH=$(git symbolic-ref --short HEAD)
+        fi
+
+        # check how many uncommitted changes
+        ## condition check is in brackets to make sure it only reports a number < zero
+        if [[ $(git status -s --porcelain --ignore-submodules=dirty) ]]; then
+                DIRTY=$(git status -s --porcelain --ignore-submodules=dirty | wc -l)
+                STATUS="${RESET}+${RED}${DIRTY}${PURPLE}"
+        else
+                STATUS=""
+        fi
+
+        PS1+="${PURPLE} (${BRANCH}${STATUS})${RESET}"
+else
+        PS1+=""
+fi
+PS1+="${BLUE} >> ${RESET}"
+
+}
+PROMPT_COMMAND=__prompt_command
+
+# }}}
+
+# COMMAND NOT FOUND {{{
+
+command_not_found_handle () {
+        lazyRandom=$((1 + RANDOM % 9))
+        case $lazyRandom in
+                1)
+                        echo "Ugh, are you done with your stupid command already?"
+                        ;;
+                2)
+                        echo "LOOK AT WHAT YOU TYPING, FFS!"
+                        ;;
+                3)
+                        echo "I think you're better off using Windows™"
+                        ;;
+                4)
+                        echo "okay, but no."
+                        ;;
+                5)
+                        echo "You make me want to die!"
+                        ;;
+                6)
+                        echo "Y U DO DIS!?"
+                        ;;
+                7)
+                        echo "YU MAKE ME CRI!"
+                        ;;
+                8)
+                        echo "U kidding me?"
+                        ;;
+                9)
+                        echo "..."
+        esac
+  return 127
+}
+
+# }}}
